/*
 * Every MSS.h entry point under the prefix MSS_BACKEND_PREFIX names, for a backend compiled beside
 * another in one exe (Windows: XA_ for miles_xaudio2.cpp, MA_ for miles_miniaudio.cpp).
 * miles_dispatch.cpp defines the plain names and forwards each to one of the two.  A function added
 * to MSS.h goes here and into mss_api.inl, or the second backend's copy collides at link.
 */

#ifndef MSS_BACKEND_NAMES_H
#define MSS_BACKEND_NAMES_H

#define MSS_BACKEND_JOIN2(a, b) a##b
#define MSS_BACKEND_JOIN(a, b) MSS_BACKEND_JOIN2(a, b)
#define MSS_BACKEND_NAME(name) MSS_BACKEND_JOIN(MSS_BACKEND_PREFIX, name)

#define AIL_startup                          MSS_BACKEND_NAME(AIL_startup)
#define AIL_shutdown                         MSS_BACKEND_NAME(AIL_shutdown)
#define AIL_quick_startup                    MSS_BACKEND_NAME(AIL_quick_startup)
#define AIL_quick_handles                    MSS_BACKEND_NAME(AIL_quick_handles)
#define AIL_set_redist_directory             MSS_BACKEND_NAME(AIL_set_redist_directory)
#define AIL_lock                             MSS_BACKEND_NAME(AIL_lock)
#define AIL_unlock                           MSS_BACKEND_NAME(AIL_unlock)
#define AIL_get_timer_highest_delay          MSS_BACKEND_NAME(AIL_get_timer_highest_delay)
#define AIL_set_file_callbacks               MSS_BACKEND_NAME(AIL_set_file_callbacks)
#define AIL_enumerate_3D_providers           MSS_BACKEND_NAME(AIL_enumerate_3D_providers)
#define AIL_open_3D_provider                 MSS_BACKEND_NAME(AIL_open_3D_provider)
#define AIL_close_3D_provider                MSS_BACKEND_NAME(AIL_close_3D_provider)
#define AIL_enumerate_filters                MSS_BACKEND_NAME(AIL_enumerate_filters)
#define AIL_set_3D_speaker_type              MSS_BACKEND_NAME(AIL_set_3D_speaker_type)
#define AIL_set_sample_processor             MSS_BACKEND_NAME(AIL_set_sample_processor)
#define AIL_set_filter_sample_preference     MSS_BACKEND_NAME(AIL_set_filter_sample_preference)
#define AIL_allocate_sample_handle           MSS_BACKEND_NAME(AIL_allocate_sample_handle)
#define AIL_release_sample_handle            MSS_BACKEND_NAME(AIL_release_sample_handle)
#define AIL_init_sample                      MSS_BACKEND_NAME(AIL_init_sample)
#define AIL_set_sample_file                  MSS_BACKEND_NAME(AIL_set_sample_file)
#define AIL_start_sample                     MSS_BACKEND_NAME(AIL_start_sample)
#define AIL_stop_sample                      MSS_BACKEND_NAME(AIL_stop_sample)
#define AIL_resume_sample                    MSS_BACKEND_NAME(AIL_resume_sample)
#define AIL_end_sample                       MSS_BACKEND_NAME(AIL_end_sample)
#define AIL_set_sample_volume_pan            MSS_BACKEND_NAME(AIL_set_sample_volume_pan)
#define AIL_sample_volume_pan                MSS_BACKEND_NAME(AIL_sample_volume_pan)
#define AIL_set_sample_playback_rate         MSS_BACKEND_NAME(AIL_set_sample_playback_rate)
#define AIL_sample_playback_rate             MSS_BACKEND_NAME(AIL_sample_playback_rate)
#define AIL_set_sample_user_data             MSS_BACKEND_NAME(AIL_set_sample_user_data)
#define AIL_sample_user_data                 MSS_BACKEND_NAME(AIL_sample_user_data)
#define AIL_register_EOS_callback            MSS_BACKEND_NAME(AIL_register_EOS_callback)
#define AIL_get_DirectSound_info             MSS_BACKEND_NAME(AIL_get_DirectSound_info)
#define AIL_allocate_3D_sample_handle        MSS_BACKEND_NAME(AIL_allocate_3D_sample_handle)
#define AIL_release_3D_sample_handle         MSS_BACKEND_NAME(AIL_release_3D_sample_handle)
#define AIL_set_3D_sample_file               MSS_BACKEND_NAME(AIL_set_3D_sample_file)
#define AIL_start_3D_sample                  MSS_BACKEND_NAME(AIL_start_3D_sample)
#define AIL_stop_3D_sample                   MSS_BACKEND_NAME(AIL_stop_3D_sample)
#define AIL_resume_3D_sample                 MSS_BACKEND_NAME(AIL_resume_3D_sample)
#define AIL_end_3D_sample                    MSS_BACKEND_NAME(AIL_end_3D_sample)
#define AIL_set_3D_sample_volume             MSS_BACKEND_NAME(AIL_set_3D_sample_volume)
#define AIL_set_3D_sample_playback_rate      MSS_BACKEND_NAME(AIL_set_3D_sample_playback_rate)
#define AIL_3D_sample_playback_rate          MSS_BACKEND_NAME(AIL_3D_sample_playback_rate)
#define AIL_set_3D_sample_distances          MSS_BACKEND_NAME(AIL_set_3D_sample_distances)
#define AIL_set_3D_sample_occlusion          MSS_BACKEND_NAME(AIL_set_3D_sample_occlusion)
#define AIL_set_3D_user_data                 MSS_BACKEND_NAME(AIL_set_3D_user_data)
#define AIL_3D_user_data                     MSS_BACKEND_NAME(AIL_3D_user_data)
#define AIL_register_3D_EOS_callback         MSS_BACKEND_NAME(AIL_register_3D_EOS_callback)
#define AIL_open_3D_listener                 MSS_BACKEND_NAME(AIL_open_3D_listener)
#define AIL_close_3D_listener                MSS_BACKEND_NAME(AIL_close_3D_listener)
#define AIL_set_3D_position                  MSS_BACKEND_NAME(AIL_set_3D_position)
#define AIL_set_3D_orientation               MSS_BACKEND_NAME(AIL_set_3D_orientation)
#define AIL_set_3D_velocity_vector           MSS_BACKEND_NAME(AIL_set_3D_velocity_vector)
#define AIL_open_stream                      MSS_BACKEND_NAME(AIL_open_stream)
#define AIL_close_stream                     MSS_BACKEND_NAME(AIL_close_stream)
#define AIL_start_stream                     MSS_BACKEND_NAME(AIL_start_stream)
#define AIL_pause_stream                     MSS_BACKEND_NAME(AIL_pause_stream)
#define AIL_set_stream_loop_count            MSS_BACKEND_NAME(AIL_set_stream_loop_count)
#define AIL_stream_loop_count                MSS_BACKEND_NAME(AIL_stream_loop_count)
#define AIL_set_stream_volume_pan            MSS_BACKEND_NAME(AIL_set_stream_volume_pan)
#define AIL_stream_volume_pan                MSS_BACKEND_NAME(AIL_stream_volume_pan)
#define AIL_stream_ms_position               MSS_BACKEND_NAME(AIL_stream_ms_position)
#define AIL_register_stream_callback         MSS_BACKEND_NAME(AIL_register_stream_callback)
#define AIL_quick_load_and_play              MSS_BACKEND_NAME(AIL_quick_load_and_play)
#define AIL_quick_unload                     MSS_BACKEND_NAME(AIL_quick_unload)
#define AIL_quick_set_volume                 MSS_BACKEND_NAME(AIL_quick_set_volume)
#define AIL_ex_start_capture                 MSS_BACKEND_NAME(AIL_ex_start_capture)
#define AIL_ex_stop_capture                  MSS_BACKEND_NAME(AIL_ex_stop_capture)
#define AIL_ex_offline_mix                   MSS_BACKEND_NAME(AIL_ex_offline_mix)
#define AIL_ex_mix_to_frame                  MSS_BACKEND_NAME(AIL_ex_mix_to_frame)
#define AIL_ex_capture_length                MSS_BACKEND_NAME(AIL_ex_capture_length)
#define AIL_ex_set_3D_linear_falloff         MSS_BACKEND_NAME(AIL_ex_set_3D_linear_falloff)
#define AIL_WAV_info                         MSS_BACKEND_NAME(AIL_WAV_info)
#define AIL_decompress_ADPCM                 MSS_BACKEND_NAME(AIL_decompress_ADPCM)
#define AIL_mem_free_lock                    MSS_BACKEND_NAME(AIL_mem_free_lock)

#endif /* MSS_BACKEND_NAMES_H */
